import React from 'react'
import styles from './index.module.css'

export default class IngredientComponent extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <main className={styles.main}>
                <h1>Hello</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
                
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia pretium urna, eget sodales magna commodo quis. Pellentesque lacinia ultricies odio id elementum. Morbi condimentum elit finibus ex ultricies sodales. Aenean vel mi metus. Donec et ultricies erat. Sed efficitur lorem sed congue volutpat. Ut lacus nunc, porta mollis pulvinar eu, tincidunt tincidunt ante. Curabitur dictum, sem vel commodo sagittis, neque leo luctus massa, eu laoreet magna felis quis purus. Nulla diam magna, facilisis tempor justo ac, porta pharetra risus. Sed ex mauris, sollicitudin a rhoncus sit amet, gravida vitae nulla. Fusce eu eros ullamcorper, pretium ligula eget, aliquet dui. Maecenas a justo mattis, posuere leo in, convallis sem. Aliquam tincidunt leo et felis rhoncus feugiat. Praesent ullamcorper posuere dui, sit amet faucibus massa tincidunt in. Sed accumsan dolor scelerisque congue laoreet.</p>
            
            </main>
        );
    }
}